# ******** Mend Unified CLI Template for Azure DevOps ********
#
# You may wish to alter this file to override the build tool and the Mend scanning technologies used (SCA, SAST or Conatiner).
#
# For more configeration options, please check the technical documentation portal:
# 📚 https://docs.mend.io/bundle/cli/page/scan_with_mend_s_unified_cli.html 
#
# ******** Description ********
# Mend SCA will automatically use package managers and file system scanning to detect open source components. 
# Mend SAST will automatically detect languages and frameworks used in your projects to scan for code weaknesses.
# Mend Containers will automatically pull the container defined and scan for open source components. 
#
name: 'mend-cli-scan'

# Define your own pipeline trigger here, however this example is for scanning on a push to the main or release branches.  
# This is the ideal time to scan so that an SBOM can be created for software releases and is also managed for released software.
trigger:
- main
- release*

pool:
  vmImage: ubuntu-latest

steps:
- script: |

    ### Build the application with your required package manager, e.g: ###
    # - task: NodeTool@0
    # - task: Maven@0
    # - task: NuGetCommand@0
    # - task: Gradle@0
    # - task: PythonScript@0

    ### Download the Mend Unified CLI ###
    echo Downloading Mend CLI
    curl https://downloads.mend.io/production/unified/latest/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
    
    ### Run SCA scan ###
    echo Start Mend SCA scan
    mend sca -u
    
    ### Run SAST scan ###
    echo Start Mend SAST scan
    mend sast
    
    ### Run Container scan ###
    echo Start Mend Container scan
    mend image ubuntu:22.10

  env:
    ### SCA and Container Environment Variables ###
    MEND_URL: $(MEND_SCA_URL)
    MEND_EMAIL: $(MEND_SCA_EMAIL)
    MEND_USER_KEY: $(MEND_SCA_USERKEY)
    MEND_ORG_UUID: $(MEND_SCA_ORG_UUID)

    ### SAST Environment Variables ###
    MEND_SAST_SERVER_URL: $(MEND_SAST_URL)
    MEND_SAST_API_TOKEN: $(MEND_SAST_API)
    MEND_SAST_ORGANIZATION: $(MEND_SAST_ORGANIZATION)

  displayName: 'Mend Unified CLI Scan'
